#!/usr/bin/env python3
"""Convert the shared compass artwork into LVGL RGB565+alpha assets."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[2]
ASSET_ROOT = ROOT / "ios/Somewhere/Resources/Assets.xcassets"
OUTPUT = ROOT / "firmware/roll-compass-board/compass_assets.h"
# The source artwork includes a top loop and a bottom flourish. The board face
# is circular, so crop around the compass body while keeping its pivot at the
# center of the output canvas.
SHELL_CROP = (100, 100, 1154, 1154)


def rgb565(r: int, g: int, b: int) -> tuple[int, int]:
    value = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return value & 0xFF, (value >> 8) & 0xFF


def bytes_for(path: Path, size: int, needle: bool = False) -> list[int]:
    source = Image.open(path).convert("RGBA")
    if needle:
        # The board face scales the needle to 48% of the shell and
        # moves its artwork hub (627, 1000) onto the shell pivot (627, 627).
        needle_size = round(size * 0.48)
        image = source.resize((needle_size, needle_size), Image.Resampling.LANCZOS)
        canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        source_hub = (627 / 1254 * needle_size, 1000 / 1254 * needle_size)
        destination = (
            round(size / 2 - source_hub[0]),
            round(size / 2 - source_hub[1]),
        )
        canvas.alpha_composite(image, destination)
        image = canvas
    else:
        image = source.crop(SHELL_CROP).resize((size, size), Image.Resampling.LANCZOS)
    output: list[int] = []
    for red, green, blue, alpha in image.getdata():
        low, high = rgb565(red, green, blue)
        output.extend((low, high, alpha))
    return output


def format_array(values: list[int]) -> str:
    lines: list[str] = []
    for start in range(0, len(values), 16):
        chunk = values[start : start + 16]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    return "\n".join(lines)


def image_block(symbol: str, values: list[int], size: int) -> str:
    return f"""static const uint8_t {symbol}Data[] = {{
{format_array(values)}
}};

static const lv_img_dsc_t {symbol} = {{
    {{LV_IMG_CF_TRUE_COLOR_ALPHA, 0, 0, {size}, {size}}},
    sizeof({symbol}Data),
    {symbol}Data,
}};
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--size", type=int, default=520)
    args = parser.parse_args()
    if args.size < 64 or args.size > 520:
        raise SystemExit("--size must be between 64 and 520")

    shell = bytes_for(
        ASSET_ROOT / "RollCompassShell.imageset/RollCompassShell@3x.png", args.size
    )
    needle = bytes_for(
        ASSET_ROOT / "RollCompassNeedle.imageset/RollCompassNeedle@3x.png",
        args.size,
        needle=True,
    )
    content = f"""#pragma once

#include <stdint.h>
#include <lvgl.h>

// Generated by scripts/firmware/generate-compass-assets.py. Keep both images
// on the same square canvas so the needle can rotate around the shared hub.
{image_block('rollCompassShellImage', shell, args.size)}
{image_block('rollCompassNeedleImage', needle, args.size)}
"""
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT} ({args.size}x{args.size} RGBA565 assets)")


if __name__ == "__main__":
    main()
