#!/usr/bin/env python3
"""Build the small tracked LVGL Hangul subset used by the board UI."""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[2]
FONT_SOURCE = ROOT / ".local-artifacts/arduino-cli/user/libraries/lvgl/src/font/korean.ttf"
OUTPUT_C = ROOT / "firmware/roll-compass-board/display_hangul_font.c"
OUTPUT_H = ROOT / "firmware/roll-compass-board/display_hangul_font.h"
FONT_SIZE = 14
GLYPH_WIDTH = 14
GLYPH_HEIGHT = 14
LINE_HEIGHT = 16
BASE_LINE = 2

# Keep this subset explicit and resource-conscious. All Korean UI copy and
# curated menu categories sent by the current phone contract are represented;
# ASCII and unsupported code points use LVGL's Montserrat fallback.
HANGUL_COPY = """
정지 계속 정지 확인 공개 남은 거리 도착 여정 완료 분류 대기 가격 미정
분류 미정 가벼운 가격대 보통 가격대 높은 가격대 보드 연결 대기 새 안내 대기
도착 공개 목적지 가까움 빨간 바늘을 따라가세요 방향 확인 중 BLE 연결됨 BLE 대기
한식 국물 요리 조용한 식사 조용한 정원 카페 일식 중식 커피 디저트 비건 면 고기
빵 분식 해산물 생선 샐러드 채식 국수 구이 찌개 전골 밥 죽 차 술 베이커리 브런치
치킨 피자 햄버거 태국 베트남 인도 멕시코 양식
"""


def format_values(values: list[int], per_line: int = 16) -> str:
    lines: list[str] = []
    for start in range(0, len(values), per_line):
        chunk = values[start : start + per_line]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    return "\n".join(lines)


def format_unicode(values: list[int], per_line: int = 12) -> str:
    lines: list[str] = []
    for start in range(0, len(values), per_line):
        chunk = values[start : start + per_line]
        lines.append("    " + ", ".join(f"{value}" for value in chunk) + ",")
    return "\n".join(lines)


def glyph_bitmap(font: ImageFont.FreeTypeFont, character: str) -> list[int]:
    image = Image.new("1", (GLYPH_WIDTH, GLYPH_HEIGHT), 0)
    draw = ImageDraw.Draw(image)
    left, top, right, bottom = font.getbbox(character)
    draw.text((-left, -top), character, font=font, fill=1)
    values: list[int] = []
    for y in range(GLYPH_HEIGHT):
        for byte_x in range(0, GLYPH_WIDTH, 8):
            value = 0
            for bit in range(8):
                if byte_x + bit < GLYPH_WIDTH and image.getpixel((byte_x + bit, y)):
                    value |= 1 << (7 - bit)
            values.append(value)
    if right - left > GLYPH_WIDTH or bottom - top > GLYPH_HEIGHT:
        raise ValueError(f"{character!r} does not fit the {GLYPH_WIDTH}x{GLYPH_HEIGHT} subset cell")
    return values


def main() -> None:
    if not FONT_SOURCE.is_file():
        raise SystemExit(f"Pinned LVGL Hangul source is missing: {FONT_SOURCE}")

    characters = sorted({character for character in HANGUL_COPY if "가" <= character <= "힣"}, key=ord)
    font = ImageFont.truetype(str(FONT_SOURCE), FONT_SIZE)
    bitmaps: list[int] = []
    descriptors = [
        "    { .bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0 },"
    ]
    for index, character in enumerate(characters):
        bitmaps.extend(glyph_bitmap(font, character))
        descriptors.append(
            "    { .bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = 0, .ofs_y = 0 },"
            % (index * (GLYPH_WIDTH * GLYPH_HEIGHT // 8), GLYPH_WIDTH * 16, GLYPH_WIDTH, GLYPH_HEIGHT)
        )
    unicode_offsets = [ord(character) - 0xAC00 for character in characters]

    OUTPUT_H.write_text(
        """#pragma once

#include <lvgl.h>

LV_FONT_DECLARE(display_hangul_font_14)
""",
        encoding="utf-8",
    )
    OUTPUT_C.write_text(
        """/* Generated by scripts/firmware/generate-hangul-font.py from the pinned LVGL Korean font. */
#include <lvgl.h>

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
%s
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
%s
};

static const uint16_t unicode_list[] = {
%s
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 0xAC00, .range_length = 0x2BA4, .glyph_id_start = 1,
        .unicode_list = unicode_list, .glyph_id_ofs_list = NULL,
        .list_length = %d, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }
};

#if LV_VERSION_CHECK(8, 0, 0)
static lv_font_fmt_txt_glyph_cache_t cache;
static const lv_font_fmt_txt_dsc_t font_dsc = {
#else
static lv_font_fmt_txt_dsc_t font_dsc = {
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LV_VERSION_CHECK(8, 0, 0)
    .cache = &cache
#endif
};

const lv_font_t display_hangul_font_14 = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = %d,
    .base_line = %d,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -2,
    .underline_thickness = 1,
    .dsc = &font_dsc,
    .fallback = &lv_font_montserrat_14
};
"""
        % (format_values(bitmaps), "\n".join(descriptors), format_unicode(unicode_offsets), len(characters), LINE_HEIGHT, BASE_LINE),
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT_H} and {OUTPUT_C} ({len(characters)} Hangul glyphs, {OUTPUT_C.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
