#!/usr/bin/env python3
"""Convert shared compass artwork into tightly bounded LVGL image assets."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[2]
ASSET_ROOT = ROOT / "ios/Somewhere/Resources/Assets.xcassets"
OUTPUT = ROOT / "firmware/roll-compass-board/compass_assets.h"
METRICS_OUTPUT = ROOT / "firmware/roll-compass-board/compass_asset_metrics.h"
# The source artwork includes a top loop and a bottom flourish. The board face
# is circular, so crop around the compass body while keeping its pivot at the
# center of the output canvas.
SHELL_CROP = (100, 100, 1154, 1154)
SOURCE_NEEDLE_HUB = (627, 1000)
SCREEN_HUB = (240, 240)
NEEDLE_SCALE_OF_DIAL = 0.48
NEEDLE_PADDING = 8


def rgb565(r: int, g: int, b: int) -> tuple[int, int]:
    value = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return value & 0xFF, (value >> 8) & 0xFF


def bytes_for(image: Image.Image) -> list[int]:
    output: list[int] = []
    for red, green, blue, alpha in image.getdata():
        low, high = rgb565(red, green, blue)
        output.extend((low, high, alpha))
    return output


def format_array(values: list[int]) -> str:
    lines: list[str] = []
    for start in range(0, len(values), 16):
        chunk = values[start : start + 16]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    return "\n".join(lines)


def image_block(symbol: str, values: list[int], width: int, height: int) -> str:
    return f"""static const uint8_t {symbol}Data[] = {{
{format_array(values)}
}};

static const lv_img_dsc_t {symbol} = {{
    {{LV_IMG_CF_TRUE_COLOR_ALPHA, 0, 0, {width}, {height}}},
    sizeof({symbol}Data),
    {symbol}Data,
}};
"""


def shell_image(path: Path, size: int) -> Image.Image:
    source = Image.open(path).convert("RGBA")
    return source.crop(SHELL_CROP).resize((size, size), Image.Resampling.LANCZOS)


def needle_image(path: Path, size: int) -> tuple[Image.Image, dict[str, int]]:
    source = Image.open(path).convert("RGBA")
    needle_size = round(size * NEEDLE_SCALE_OF_DIAL)
    resized = source.resize((needle_size, needle_size), Image.Resampling.LANCZOS)
    scale_x = needle_size / source.width
    scale_y = needle_size / source.height
    transformed_hub_x = round(SOURCE_NEEDLE_HUB[0] * scale_x)
    transformed_hub_y = round(SOURCE_NEEDLE_HUB[1] * scale_y)
    alpha_bounds = resized.getchannel("A").getbbox()
    if alpha_bounds is None:
        raise RuntimeError("needle source has no visible alpha pixels")
    left = max(0, alpha_bounds[0] - NEEDLE_PADDING)
    top = max(0, alpha_bounds[1] - NEEDLE_PADDING)
    right = min(resized.width, alpha_bounds[2] + NEEDLE_PADDING)
    bottom = min(resized.height, alpha_bounds[3] + NEEDLE_PADDING)
    cropped = resized.crop((left, top, right, bottom))
    pivot_x = transformed_hub_x - left
    pivot_y = transformed_hub_y - top
    return cropped, {
        "needle_pivot_x": pivot_x,
        "needle_pivot_y": pivot_y,
        "needle_screen_x": SCREEN_HUB[0] - pivot_x,
        "needle_screen_y": SCREEN_HUB[1] - pivot_y,
    }


def metrics_header(shell: Image.Image, needle: Image.Image, metrics: dict[str, int]) -> str:
    return f"""#pragma once

#include <stdint.h>

// Generated by scripts/firmware/generate-compass-assets.py.
namespace roll_compass_assets {{

constexpr int16_t kShellWidth = {shell.width};
constexpr int16_t kShellHeight = {shell.height};
constexpr int16_t kNeedleWidth = {needle.width};
constexpr int16_t kNeedleHeight = {needle.height};
constexpr int16_t kNeedlePivotX = {metrics['needle_pivot_x']};
constexpr int16_t kNeedlePivotY = {metrics['needle_pivot_y']};
constexpr int16_t kScreenHubX = {SCREEN_HUB[0]};
constexpr int16_t kScreenHubY = {SCREEN_HUB[1]};
constexpr int16_t kNeedleScreenX = {metrics['needle_screen_x']};
constexpr int16_t kNeedleScreenY = {metrics['needle_screen_y']};

}}  // namespace roll_compass_assets
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--size", type=int, default=480)
    args = parser.parse_args()
    if args.size != 480:
        raise SystemExit("the circular board asset size must be 480")

    shell = shell_image(
        ASSET_ROOT / "RollCompassShell.imageset/RollCompassShell@3x.png", args.size
    )
    needle, metrics = needle_image(
        ASSET_ROOT / "RollCompassNeedle.imageset/RollCompassNeedle@3x.png",
        args.size,
    )
    shell_bytes = bytes_for(shell)
    needle_bytes = bytes_for(needle)
    content = f"""#pragma once

#include <stdint.h>
#include <lvgl.h>

// Generated by scripts/firmware/generate-compass-assets.py.
{image_block('rollCompassShellImage', shell_bytes, shell.width, shell.height)}
{image_block('rollCompassNeedleImage', needle_bytes, needle.width, needle.height)}
"""
    OUTPUT.write_text(content, encoding="utf-8")
    METRICS_OUTPUT.write_text(metrics_header(shell, needle, metrics), encoding="utf-8")
    print(
        f"Wrote {OUTPUT} (shell {shell.width}x{shell.height}, "
        f"needle {needle.width}x{needle.height})"
    )
    print(f"Wrote {METRICS_OUTPUT}")


if __name__ == "__main__":
    main()
